### ISSUE TITLE
Pre user jobs for Rich

### ISSUE THREAD

**Issue by richfitz** [rsheets/rexcel#14]
- cursory formula parsing
- sort out crawl through enron

**Comment by jennybc** [comment]
Are you willing to be the one to turn on travis (#16) and appveyor (#17)?

**Comment by richfitz** [comment]
sure

**Comment by jennybc** [comment]
We'll be failing there for a while I suspect, but it would still be progress to get set up and fail due to our tests 😬 vs. all the other reasons I usually fail at first.

**Comment by oneillkza** [comment]
Take a look at #23 for a resolution to that (for Travis, anyway.) :)
