### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by jennybc** [rsheets/rexcel#15]
@richfitz 

I have made progress on the tests, working towards the goal of passing R CMD check and succeeding on travis and appveyor.

Happening in ~~https://github.com/rsheets/rexcel/tree/pass-existing-tests~~ master.

A couple things:
- I disabled the test re: an xlsx from Google Sheets. The tested function, `xlsx_internal_sheet_name()`, no longer seems to work the way it did when this test was created? It doesn't seem worth fixing, since we're about to do some fiddling with worksheet metadata anyway. Just commented out for now. We can bring it back online soon. I think we should make this information available in the linen object. And then consult it in this test.
- Do we have a policy re: testing and exported functions? Will we test unexported functions directly? If they are test-worthy are they export-worthy?
- I started using `rprojroot` which I hope you'll allow 😬. I really think it's a sane way to deal with directories relative to a project's root. However at the moment I use the default criterion to locate project root (it looks for a DESCRIPTION file), which works during interactive development and with `devtools::test()` but not during R CMD check. I've asked @krlmlr for thoughts on this. If he has no remedies, I will obviously handle paths differently.
- On my machine, two of `readxl`'s sheets are not equal to what we get with `rexcel`. Does that surprise you? Does that test pass for you right now?
- We are not even trying the comparison on 2 of `readxl`'s test sheets and the explanatory comment from you says something about Numbers. Is there something I should do with Excel to see if we can bring these online?
- Why is the helper file called `helper-jailbreakr.R`?

**Comment by jennybc** [comment]
I've added some really crude tests where we just try to read all example sheets w/o fatal error. I'm removing Ekaterinburg from the set until (a) we at least attempt to deal with its namespacing; and (b) we do something about how big it is, which makes the tests unnecessarily slow.

**Comment by richfitz** [comment]
I'm working on the namespacing for Ekaterinburg but the speed thing is going to remain an issue I think.

**Comment by jennybc** [comment]
You mean Ekaterinburg is always going to be unpalatable for testing because of its size? And if we open it in Excel to make it smaller, it loses all of its wonderful weirdness?

We could actually hand edit the darn thing and remove the bulk of the data. But keep its crazy namespacing and overall structure. Hmmm... I'm not even sure if that would work. I wonder if Excel is finicky about how things get zipped up. My one attempt at `.tar.gz` surgery on an R package did not fly at win-builder or CRAN.

**Comment by richfitz** [comment]
Excel should be fine with being unzipped/rezipped.  I'll have a look at doing that as I finish this up.

**Comment by jennybc** [comment]
Revisiting the tests. To be more specific, these are the two failures alluded to above (there's a 3rd but I'm hoping to resolve):

 * new_line_errors.xlsx
 * types.xlsx

**Comment by richfitz** [comment]
Tests now pass at last
