### ISSUE TITLE
don't unzip xlsx repeatedly

### ISSUE THREAD

**Issue by jennybc** [rsheets/rexcel#20]
Right now we unzip xlsx into a temporary directory multiple times inside `rexcel_read_workbook()`. That should pretty easy to avoid if we generalize what `path` can be in `xlsx_read_file()`. If it's xlsx, unzip it. If not, do nothing. Then attempt to read the specified file. At the start of `rexcel_read_workbook()` we could unpack the xlsx to a temp dir and pass that path down to the functions that read all the XML files.

Alternatively, maybe we don't need to do all this unzipping? Check out `unz()` in base.

Usage:

``` r
unz(description, filename, open = "", encoding = getOption("encoding"))
```

From the docs:

> `unz` reads (only) single files within zip files, in binary mode. The description is the full path to the zip file, with ‘.zip’ extension if required.

**Comment by richfitz** [comment]
In the read function

```r
xlsx_read_file <- function(path, file) {
  tmp <- tempfile()
  dir.create(tmp)
  ## Oh boy more terrible default behaviour.
  filename <- tryCatch(utils::unzip(path, file, exdir=tmp),
                       warning=function(e) stop(e))
  on.exit(unlink(tmp, recursive=TRUE))
  xml2::read_xml(filename)
}
```

we only read a single file.  We could swap that out for `base::unz` and feed the result into the XML reading functions, but there would be some faff involved with closing connections (and what do do when the files aren't read correctly).

One downside of the current approach is that the files are left hanging around in the temporary directory (but will be deleted on session exit).  We could arrange to delete these after reading.

The bottleneck at the moment is one of the `xml2` functions, so there's no performance gain here.
