### ISSUE TITLE
Be able to parse underscore-encoded XML characters (e.g. _x000D_ )

### ISSUE THREAD

**Issue by oneillkza** [rsheets/rexcel#24]
This is essentially a duplicate of a readxl issue: hadley/readxl#51

It is causing failure of the testthat test on  `new_line_errors.xlsx`, since readxl parses `_x000D_` as `\r\r`:

``` r
> readxl
                                                                                                       column_name
1 first line of text \r\r\nsecond line of text \r\r\ni don't know what type of line feed I've used \r\r\nlast line
2                                                              Will show "_x000D_" in every new line in cell above
> us
                                                                                                                column_name
1 first line of text _x000D_\nsecond line of text _x000D_\ni don't know what type of line feed I've used _x000D_\nlast line
2                                                                 Will show "_x005F_x000D_" in every new line in cell above
```

In general, the solution seems to be to parse instances of the string `_xNNNN_` as encoded XML characters. Unfortunately I'm not familiar enough with rexcel's parser to attempt this, but there is a link to a commit in that readxl issue which may help.

**Comment by jennybc** [comment]
Hi @oneillkza, thanks for digging into some of our issues 😀! This one and the others. It is helpful. I'm about to enter intense STAT 545 mode but we will be back in touch and engage!
