### ISSUE TITLE
minimal fuss way to read file inside xlsx?

### ISSUE THREAD

**Issue by jennybc** [rsheets/rexcel#9]
@richfitz Is there a way, from R, to read a single file out of the zip archive that is an xlsx "file" **without unpacking the entire thing to a temporary directory**? Do you know off-hand what `readxl` does?

**Comment by jennybc** [comment]
Reading the [docs for `base::unzip()`](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/unzip.html), I see I can list files, extract single files, etc. Will play with that.

**Comment by richfitz** [comment]
Yes! The functions `xlsx_read_file` and `xlsx_read_file_if_exists` do this while working around some awful behaviour of `unzip`.

**Comment by jennybc** [comment]
Oh right. I guess my real question is: is it unavoidable to extract to a (temp) file? I'm wondering if we can read xml straight out of those files.

**Comment by richfitz** [comment]
Any reason you really want to avoid the temp file?  It's probably possible but I'm not sure what the upside is given you'll have to the XML parser to it, and R's textConnection objects (say if you had a string) are slower than temporary files.

**Comment by jennybc** [comment]
No particular reason. This is probably just me thinking out loud as I figure out what's what.

**Comment by richfitz** [comment]
Watch out or I'll spend a bunch of time wrapping libzip 🐃 🔪 🔜 🐩
